### ISSUE TITLE
file import bugged

### ISSUE THREAD

**Issue by jauhl** [jauhl/mecEdit#3]
Importing `JSON` files is bugged in chrome 72^ (edit: v71.0.3578.98 x64 confirmed working as intended). You have to be really fast to confirm your action or else the file-explorer won't open anymore. Firefox lets you take your sweet time.

**Comment by goessner** [comment]
importing by dynamic `<script>` elements ... ? Should be no bug with `mec2`.

**Comment by jauhl** [comment]
This issue is not mec2 related. It is a bug that appears when you try to upload (File > Import Mode from JSONl) a JSON model from your local filesystem. mecEdit then asks with a `confirm()` if you are sure that you want to discard the current model. Canceling then calls `preventDefault()` so that the fileexplorer does not open. This worked flawlessly up to Chrome 70 and still does in Firefox. In the current version of Chrome you have to be quick to confirm the prompt or the fileexplorer won't open even if you agree.

**Comment by jauhl** [comment]
Seems to be fixed in Chrome 74.
