### ISSUE TITLE
Adding Pictures

### ISSUE THREAD

**Issue by Pasquale19** [jauhl/mecEdit#5]
Hi. I currently discovered your Web App. Since a long time, I was looking for a great linkage App that I can use to create some nice simulation and your app is pretty nice. Yesterday I discovered in the example "Pumpjack" that it is possible to include pictures. Is it possible to upload and use my own pictures? Editing the .json code didn’t work...

Also I am interested in adding some of my own features. However I am pretty new to Javascript and Webapps. Is it possible to download your code and run it with Visual Studio? I am sorry for this beginner question, but I don’t know where to start. By the way if your are a german you can answer me in “Deutsch” 😉. Do you you have an E-mail address, where I can contact you?

**Comment by jauhl** [comment]
Hallo.
Bilder kannst du, wie im Beispiel Pumpjack gezeigt, als shapes einfügen. Dazu musst du im `uri` Parameter die vollständige Webadresse angeben. Im Beispiel ist der Pfad zum Bild relativ zur `index.html` von mecedit und das geht nur weil alle Dateien bei Github im selben Repository liegen. Wenn du deine eigenen Bilder hochlädst musst du den vollständigen Pfad angeben. Hier ein Beispielmodel mit einem Bild das auf imgur.com gehostet ist:

```json
{
  "shapes": [
    { "type":"img","uri":"https://i.imgur.com/wbrpYEH.jpeg"}
  ]
}
```

Um das Repository runterzuladen kannst du es mit [git](https://git-scm.com/) clonen oder auf der Hauptseite auf den grünen _Code_ Button klicken und dann auf _Download ZIP_. Javascript wird nicht kompiliert (bzw. geschieht das zur Laufzeit) und da mecedit rein clientseitig läuft, reicht es wenn du einfach die Datei `index.html` mit deinem Browser öffnest. 
Für's Coden mit JS eine IDE wie Visual Studio zu benutzen ist ein bisschen wie mit Kanonen auf Spatzen zu schießen. Schau dir stattdessen mal einen featurereichen Texteditor wie z.B. [VS Code](https://code.visualstudio.com/) an.

Ich bin unter jan.uhlig [bei] web.de erreichbar.
